# Generated by Django 4.2.16 on 2024-09-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(db_column='task_id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=200)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('completed', models.BooleanField(db_column='completed', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('completed_at', models.DateTimeField(blank=True, db_column='completed_at', null=True)),
            ],
        ),
    ]
